// Generated by training/export_model.py; do not edit by hand.
#pragma once
#include <math.h>
#include <stddef.h>
namespace BeeGuardModel {
constexpr size_t FEATURE_COUNT=40;
constexpr size_t NODE_COUNT=11;
constexpr size_t CLASS_COUNT=3;
const char* const CLASS_NAMES[CLASS_COUNT]={"ALERT", "HEALTHY", "PROBLEM"};
static const int LEFT[NODE_COUNT]={1,2,3,4,-1,-1,-1,8,-1,-1,-1};
static const int RIGHT[NODE_COUNT]={10,7,6,5,-1,-1,-1,9,-1,-1,-1};
static const int FEATURE[NODE_COUNT]={23,7,14,33,-2,-2,-2,12,-2,-2,-2};
static const float THRESHOLD[NODE_COUNT]={9.91128422e-06f,1.70618159f,0.763739496f,0.0624479968f,-2.0f,-2.0f,-2.0f,75.7547684f,-2.0f,-2.0f,-2.0f};
static const float LEAF_PROBS[NODE_COUNT][CLASS_COUNT]={{0.333333333f,0.333333333f,0.333333333f},{0.0f,0.5f,0.5f},{0.0f,0.714587738f,0.285412262f},{0.0f,0.957507082f,0.0424929178f},{0.0f,1.0f,0.0f},{0.0f,0.634146341f,0.365853659f},{0.0f,0.0f,1.0f},{0.0f,0.169381107f,0.830618893f},{0.0f,1.0f,0.0f},{0.0f,0.0f,1.0f},{1.0f,0.0f,0.0f}};
inline int predict(const float *x,float *confidence){int n=0;while(LEFT[n]!=RIGHT[n])n=(x[FEATURE[n]]<=THRESHOLD[n])?LEFT[n]:RIGHT[n];int k=0;for(int c=1;c<CLASS_COUNT;c++)if(LEAF_PROBS[n][c]>LEAF_PROBS[n][k])k=c;*confidence=LEAF_PROBS[n][k];return k;}
// Order: rms_mean, rms_max, rms_min, rms_std, db_mean, db_max, db_min, db_std, dominant_freq_mean, dominant_freq_max, dominant_freq_min, dominant_freq_std, dominant_freq_median, band_100_300_energy, band_100_300_relative, band_300_600_energy, band_300_600_relative, band_600_1000_energy, band_600_1000_relative, band_1000_2000_energy, band_1000_2000_relative, band_2000_4000_energy, band_2000_4000_relative, band_4000_8000_energy, band_4000_8000_relative, spectral_centroid_mean, spectral_centroid_std, spectral_bandwidth_mean, spectral_bandwidth_std, spectral_rolloff_mean, spectral_rolloff_std, spectral_flatness_mean, spectral_flatness_std, zero_crossing_mean, zero_crossing_std, energy_200_270, energy_relative_200_270, peak_frequency_200_300, energy_below_1080, energy_relative_below_1080
}
